config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :post_tag_relations, dependent: :destroy
    has_many :tags, through: :post_tag_relations, dependent: :destroy
end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :post_tag_relations, dependent: :destroy
    has_many :posts, through: :post_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        has_many :posts, dependent: :destroy
        has_many :likes, dependent: :destroy
        has_many :liked_posts, through: :likes, source: :post 
        has_many :comments, dependent: :destroy
        validates :name, presence: true 
        validates :profile, length: { maximum: 200 }
        def already_liked?(post)
          self.likes.exists?(post_id: post.id)
        end       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      post = Post.find(params[:post_id])
      comment = post.comments.build(comment_params) 
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path) 
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path) 
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]
    def index
      @posts= Post.all
      @tags = Tag.all
      post_ids = []

      if params[:tag_ids]
        params[:tag_ids].each do |key, value| 
          Tag.find_by(name: key).posts.each { |p| post_ids << p.id } if value == "1"
        end
        post_ids.uniq!
        @posts.where!(id: post_ids) if post_ids.present?
      end
      @posts.where!("age LIKE ? ",'%' + params[:search] + '%') if params[:search]
    end
    def new
        @post = Post.new
      end
    
      def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        if post.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      def show
        @post = Post.find(params[:id])
        @comments = @post.comments
        @comment = Comment.new
      end
      def edit
        @post = Post.find(params[:id])
      end
      def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
      end
      def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
      end
      private
      def post_params
        params.require(:post).permit(:name, :age, :about, :image,:lat,:lng, tag_ids: [])
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Geektwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>GeekTwitter</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ホーム", posts_path %></li>
        <li><%= link_to "新規投稿",new_post_path %></li>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/edit.html.erb
<%= form_for @post do |f| %>
    <div class="field">
    <%= f.label :場所 %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  
<div class="field">
    <%= f.label :年齢  %>
    <%= f.select :age, 
    [["A", "A"], 
    ["B", "B"], 
    ["C", "C"]], include_blank: "選択して下さい" %>
  </div>
  <div class="field">
    <%= f.label :コメント  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

  <%= f.submit "編集する" %>
<% end %>

app/views/posts/index.html.erb
<h1>自分の題名</h1>
<h3>一覧ページ</h3>
<h3>投稿を検索</h3>
<% if user_signed_in? %>
<%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <%= select_tag :search, options_for_select([['選択'],['A'], ['B'], ['C']]) %>
  <% Tag.all.each do |t| %>
    <li><%= check_box :tag_ids, t.name %><%= t.name %></li>
<% end %>
  <%= submit_tag '検索する'  %>
<% end %>
<%= link_to "新規投稿へ", new_post_path %>
<div class="tweets-container">
  <% @posts.each do |t| %>
    <div class="tweet">
    <%= link_to t.user.name, user_path(t.user.id) %>
    <%= t.name %>
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <%= t.age %>
      <%= t.about %>
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
            <i class="fas fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
            <i class="far fa-heart"></i><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
  <i class="far fa-heart"></i><%= t.likes.count %>
  <% end %>
      <%= link_to "詳細へ", post_path(t.id) %>
      <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_post_path(t.id) %>
      <%= button_to "削除する", post_path(t.id), method: :delete %> 
      <% end %> 
      </div>
  <% end %>
</div>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      let latlng = new google.maps.LatLng(38.60, 139.5);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

//複数マーカー ここから
      <% @posts.each do |post|%>
        ( function() { 
          let markerLatLng = { lat: <%= post.lat %>, lng: <%= post.lng %> }; // 緯度経度のデータ作成
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });
//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= post_url(post.id) %>' target='_blank'><%= post.name %></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      <% end %>
      //複数マーカー ここまで  
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC1ihFY7GiAOUN2hjjbcUygvoEOovVxdSQ&callback=initMap" async defer></script>

app/views/posts/new.html.erb
<h1>(自分の題名)</h1>
<h3>新規投稿ページ</h3>
<%= form_for @post do |f| %>
    <div class="field">
    <%= f.label :場所 %>
    <%= f.text_field :name, :size => 30 %>
  </div>
  <div class="field">
  <%= f.label :image %>
  <%= f.file_field :image %>
</div>
  
<div class="field">
    <%= f.label :年齢  %>
    <%= f.select :age, 
    [["A", "A"], 
    ["B", "B"], 
    ["C", "C"]], include_blank: "選択して下さい" %>
  </div>
  <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>
  <div class="field">
    <%= f.label :コメント  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>
  <input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
  <%= f.label :lat,"緯度" %>
  <%= f.text_field :lat,:value =>"緯度", id: :lat %>
  <%= f.label :lng,"経度" %>
  <%= f.text_field :lng,:value =>"経度", id: :lng %>
  <%= f.submit "投稿する" %>
<% end %>
<h2>Map</h2>


<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	// ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC1ihFY7GiAOUN2hjjbcUygvoEOovVxdSQ&callback=initMap" async defer></script>
<%= link_to "一覧に戻る", posts_path %>

app/views/posts/show.html.erb
<h1>GeekTwitter</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
<p><%= @post.name %></p>
<%= image_tag @post.image_url, size: "250x200" if @post.image? %>
<p><%= @post.age %></p>
<p><%= @post.about %></p>
<p><%= @post.created_at %></p>
<% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
        <%= link_to post_like_path(@post), method: :delete do %>
            <i class="fas fa-heart"></i><%= @post.likes.count %>
        <% end %>
      <% else %>
        <%= link_to post_likes_path(@post), method: :post do %>
          <i class="far fa-heart"></i><%= @post.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"></i><%= @post.likes.count %>
    <% end %>
</div>
<h2>いいねしたユーザー</h2>
<% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
<% @post.tags.each do |tag| %>
  <span><%= tag.name %></span>
<% end %>
<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>
<%= link_to "Tweet一覧に戻る", posts_path %>
<%= link_to "編集する", edit_post_path(@post.id) %>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<!-- js部分 -->
<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: <%= @post.lat %>, lng: <%= @post.lng %>},
    zoom: 15,
  });

   marker = new google.maps.Marker({
    position:  {lat: <%= @post.lat %>, lng: <%= @post.lng %>},
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC1ihFY7GiAOUN2hjjbcUygvoEOovVxdSQ&callback=initMap" async defer></script>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
<div class="share">
  <%= link_to "Log in", new_session_path(resource_name), class: "field_input"%><br />
</div>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
<% end %>


<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_posts.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
<% end %>
<%= link_to "Tweet一覧に戻る", posts_path %>